import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type SeedTemplate = {
  name: string;
  category: string;
  description: string;
  steps: string[];
  order: number;
};

const templates: SeedTemplate[] = [
  {
    name: "Selam Verme",
    category: "Sosyal Beceri",
    description: "Karşılaşma anında uygun selamlaşma davranışı için zincirleme beceri analizi.",
    order: 1,
    steps: [
      "Karşısındaki kişiyi fark eder.",
      "Kişiye yönelir.",
      "Göz teması kurar.",
      "Uygun yüz ifadesi oluşturur.",
      "Uygun selamlaşma sözcüğünü seçer.",
      "Selam verir.",
      "Gerekirse el sallar veya el uzatır.",
      "Karşı tarafın tepkisini bekler.",
      "Verilen selamı dinler.",
      "Etkileşimi uygun şekilde sonlandırır.",
    ],
  },
  {
    name: "Kendini Tanıtma",
    category: "Sosyal Beceri",
    description: "Yeni biriyle tanışma durumunda kendini tanıtma becerisi için zincirleme beceri analizi.",
    order: 2,
    steps: [
      "Karşısındaki kişiye yönelir.",
      "Göz teması kurar.",
      "Selam verir.",
      "Adını söyler.",
      "Soyadını söyler (gerekiyorsa).",
      "Yaşını söyler.",
      "Sınıfını veya okulunu söyler.",
      "Kısa bir ilgi alanını paylaşır.",
      "Karşı tarafın konuşmasını bekler.",
      "Sohbeti uygun şekilde sürdürür.",
    ],
  },
  {
    name: "Sıra Bekleme",
    category: "Sosyal Beceri",
    description: "Ortak alanlarda sırasını bekleme becerisi için zincirleme beceri analizi.",
    order: 3,
    steps: [
      "Sıra olduğunu fark eder.",
      "Sıranın sonuna geçer.",
      "Kendi sırasını belirler.",
      "Başkasının önüne geçmez.",
      "Bekleme sırasında bulunduğu yerde kalır.",
      "Sessiz şekilde bekler.",
      "Başkalarını rahatsız etmez.",
      "Sırası geldiğini fark eder.",
      "Öne geçer.",
      "İşlemini gerçekleştirir.",
    ],
  },
  {
    name: "Yardım İsteme",
    category: "Sosyal Beceri",
    description: "İhtiyaç anında uygun şekilde yardım isteme becerisi için zincirleme beceri analizi.",
    order: 4,
    steps: [
      "Yardıma ihtiyaç duyduğunu fark eder.",
      "Yakınındaki uygun kişiyi belirler.",
      "Kişiye yönelir.",
      "Göz teması kurar.",
      "Nazikçe seslenir.",
      "Yardım isteğini ifade eder.",
      "Yardımı bekler.",
      "Yardımı kabul eder.",
      "Yardım sonrasında teşekkür eder.",
      "Etkinliğe devam eder.",
    ],
  },
  {
    name: "Teşekkür Etme",
    category: "Sosyal Beceri",
    description: "Destek veya yardım sonrasında teşekkür etme becerisi için zincirleme beceri analizi.",
    order: 5,
    steps: [
      "Yardım veya destek aldığını fark eder.",
      "Yardım eden kişiye yönelir.",
      "Göz teması kurar.",
      "Gülümser.",
      "\"Teşekkür ederim.\" der.",
      "Uygun ses tonu kullanır.",
      "Gerekirse beden dili kullanır.",
      "Karşı tarafın tepkisini bekler.",
      "Sohbeti uygun şekilde sürdürür.",
      "Ortamdan uygun şekilde ayrılır.",
    ],
  },
  {
    name: "Özür Dileme",
    category: "Sosyal Beceri",
    description: "Hata sonrasında özür dileme becerisi için zincirleme beceri analizi.",
    order: 6,
    steps: [
      "Hata yaptığını fark eder.",
      "İlgili kişiye yönelir.",
      "Göz teması kurar.",
      "Sakinleşir.",
      "\"Özür dilerim.\" der.",
      "Hatasını açıklar.",
      "Gerekirse telafi önerir.",
      "Karşı tarafın cevabını dinler.",
      "Uygun tepki verir.",
      "Davranışını düzeltir.",
    ],
  },
  {
    name: "Sohbet Başlatma",
    category: "Sosyal Beceri",
    description: "Karşılıklı iletişim başlatma becerisi için zincirleme beceri analizi.",
    order: 7,
    steps: [
      "Sohbet edeceği kişiyi belirler.",
      "Yanına gider.",
      "Göz teması kurar.",
      "Selam verir.",
      "Uygun bir konuşma konusu seçer.",
      "İlk cümleyi söyler.",
      "Karşı tarafı dinler.",
      "Soru sorar.",
      "Sohbeti sürdürür.",
      "Sohbeti uygun şekilde sonlandırır.",
    ],
  },
  {
    name: "Sohbeti Sürdürme",
    category: "Sosyal Beceri",
    description: "Karşılıklı konuşmayı sürdürme becerisi için zincirleme beceri analizi.",
    order: 8,
    steps: [
      "Konuşanı dinler.",
      "Göz teması kurar.",
      "Söz kesmez.",
      "Konuyla ilgili cevap verir.",
      "Yeni soru sorar.",
      "Uygun ses tonu kullanır.",
      "Konu dışına çıkmaz.",
      "Karşı tarafın konuşmasını bekler.",
      "Sohbeti sürdürür.",
      "Uygun şekilde bitirir.",
    ],
  },
  {
    name: "Duygularını Uygun Şekilde İfade Etme",
    category: "Sosyal Beceri",
    description: "Duyguları uygun ve sosyal kabul edilebilir şekilde ifade etme becerisi için zincirleme beceri analizi.",
    order: 9,
    steps: [
      "Duygusunu fark eder.",
      "Duruma uygun kişiyi seçer.",
      "Kişiye yönelir.",
      "Göz teması kurar.",
      "Duygusunu sözel olarak ifade eder.",
      "Gerekirse nedenini açıklar.",
      "Sakin ses tonu kullanır.",
      "Karşı tarafı dinler.",
      "Çözüm önerilerini değerlendirir.",
      "Etkinliğe devam eder.",
    ],
  },
  {
    name: "Grup Etkinliğine Katılma",
    category: "Sosyal Beceri",
    description: "Grup içinde uygun şekilde etkinliğe katılma becerisi için zincirleme beceri analizi.",
    order: 10,
    steps: [
      "Grubu fark eder.",
      "Katılmak istediğini ifade eder.",
      "İzin ister.",
      "Gruba katılır.",
      "Kuralları dinler.",
      "Kurallara uyar.",
      "Sırası geldiğinde etkinliğe katılır.",
      "Arkadaşlarıyla iş birliği yapar.",
      "Etkinliği tamamlar.",
      "Grup etkinliğini uygun şekilde sonlandırır.",
    ],
  },
  {
    name: "Göz Teması Kurma",
    category: "Sosyal Beceri",
    description: "Etkileşim sırasında uygun göz teması kurma becerisi için zincirleme beceri analizi.",
    order: 11,
    steps: [
      "Karşısındaki kişiyi fark eder.",
      "Kişiye yönelir.",
      "Başını kişiye çevirir.",
      "Gözlerini kişinin yüzüne yöneltir.",
      "En az 2 saniye göz teması kurar.",
      "Konuşma boyunca göz temasını sürdürür.",
      "Ara sıra göz temasını yeniler.",
      "Konuşmayı dinlemeye devam eder.",
      "Dikkatini kişide tutar.",
      "Etkileşim sonunda göz temasını uygun şekilde sonlandırır.",
    ],
  },
  {
    name: "Ortak Dikkat Kurma",
    category: "Sosyal Beceri",
    description: "Bir nesne veya olay üzerinde başkasıyla dikkat paylaşma becerisi için zincirleme beceri analizi.",
    order: 12,
    steps: [
      "Ortamdaki nesneyi fark eder.",
      "Karşısındaki kişiyi fark eder.",
      "Kişiye bakar.",
      "Nesneye bakar.",
      "Tekrar kişiye bakar.",
      "Parmağıyla gösterir veya işaret eder.",
      "Sözel ifade kullanır.",
      "Karşı tarafın tepkisini bekler.",
      "Ortak dikkati sürdürür.",
      "Etkileşimi tamamlar.",
    ],
  },
  {
    name: "Oyuna Katılma",
    category: "Sosyal Beceri",
    description: "Oynayan bir gruba uygun şekilde katılma becerisi için zincirleme beceri analizi.",
    order: 13,
    steps: [
      "Oynayan grubu fark eder.",
      "Yanlarına yaklaşır.",
      "Uygun zamanda bekler.",
      "\"Ben de oynayabilir miyim?\" der.",
      "Cevabı bekler.",
      "Kabul edilirse oyuna katılır.",
      "Oyunun kurallarını takip eder.",
      "Arkadaşlarıyla etkileşim kurar.",
      "Oyunu sürdürür.",
      "Oyundan uygun şekilde ayrılır.",
    ],
  },
  {
    name: "Oyuncak Paylaşma",
    category: "Sosyal Beceri",
    description: "Kullandığı bir oyuncağı arkadaşıyla paylaşma becerisi için zincirleme beceri analizi.",
    order: 14,
    steps: [
      "Oyuncağı kullanmaktadır.",
      "Arkadaşının isteğini fark eder.",
      "Arkadaşına yönelir.",
      "Oyuncağı uzatır.",
      "Nazik ifade kullanır.",
      "Oyuncağı paylaşır.",
      "Beklemeyi kabul eder.",
      "Sırası gelince oyuncağı geri alır.",
      "Arkadaşına teşekkür eder.",
      "Oyuna devam eder.",
    ],
  },
  {
    name: "İzin İsteme",
    category: "Sosyal Beceri",
    description: "Bir davranışı gerçekleştirmeden önce izin isteme becerisi için zincirleme beceri analizi.",
    order: 15,
    steps: [
      "Yapmak istediği davranışı belirler.",
      "Yetkili kişiyi belirler.",
      "Kişiye yaklaşır.",
      "Göz teması kurar.",
      "Nazikçe seslenir.",
      "İzin ister.",
      "Cevabı bekler.",
      "Cevaba uygun davranır.",
      "Teşekkür eder.",
      "Davranışı gerçekleştirir.",
    ],
  },
  {
    name: "Hayır Deme",
    category: "Sosyal Beceri",
    description: "İstemediği bir duruma karşı uygun şekilde hayır deme becerisi için zincirleme beceri analizi.",
    order: 16,
    steps: [
      "İstemediği durumu fark eder.",
      "Sakin kalır.",
      "Karşısındaki kişiye yönelir.",
      "Göz teması kurar.",
      "\"Hayır.\" der.",
      "Nazik ifade kullanır.",
      "Gerekirse nedenini açıklar.",
      "Kararını sürdürür.",
      "Baskıya uygun tepki verir.",
      "Ortamdan uygun şekilde ayrılır.",
    ],
  },
  {
    name: "Hayırı Kabul Etme",
    category: "Sosyal Beceri",
    description: "Aldığı olumsuz bir cevabı sakin şekilde kabul etme becerisi için zincirleme beceri analizi.",
    order: 17,
    steps: [
      "\"Hayır\" cevabını duyar.",
      "Karşı tarafı dinler.",
      "Sakin kalır.",
      "Israr etmez.",
      "Uygun cevap verir.",
      "Alternatif öneriyi dinler.",
      "Alternatifi kabul eder.",
      "Olumsuz davranış göstermez.",
      "Etkinliğe devam eder.",
      "Durumu kabul eder.",
    ],
  },
  {
    name: "Arkadaşını Davet Etme",
    category: "Sosyal Beceri",
    description: "Bir arkadaşını ortak bir etkinliğe davet etme becerisi için zincirleme beceri analizi.",
    order: 18,
    steps: [
      "Arkadaşını belirler.",
      "Yanına gider.",
      "Göz teması kurar.",
      "Selam verir.",
      "Etkinliği söyler.",
      "Davette bulunur.",
      "Cevabı bekler.",
      "Kabul edilirse teşekkür eder.",
      "Etkinliği başlatır.",
      "Etkinliği birlikte sürdürür.",
    ],
  },
  {
    name: "Daveti Kabul Etme",
    category: "Sosyal Beceri",
    description: "Aldığı bir daveti uygun şekilde kabul etme becerisi için zincirleme beceri analizi.",
    order: 19,
    steps: [
      "Daveti dinler.",
      "Daveti anlar.",
      "Göz teması kurar.",
      "Kabul edeceğine karar verir.",
      "\"Evet.\" der.",
      "Gülümser.",
      "Etkinliğe hazırlanır.",
      "Davet eden kişiyle birlikte hareket eder.",
      "Etkinliğe katılır.",
      "Etkinliği tamamlar.",
    ],
  },
  {
    name: "Daveti Reddetme",
    category: "Sosyal Beceri",
    description: "Aldığı bir daveti nazikçe reddetme becerisi için zincirleme beceri analizi.",
    order: 20,
    steps: [
      "Daveti dinler.",
      "Düşünür.",
      "Göz teması kurar.",
      "Nazik ifade kullanır.",
      "\"Hayır, teşekkür ederim.\" der.",
      "Gerekirse nedenini açıklar.",
      "Alternatif önerir.",
      "Karşı tarafı dinler.",
      "Nazik şekilde ayrılır.",
      "Etkinliğine devam eder.",
    ],
  },
  {
    name: "Kurallara Uyma",
    category: "Sosyal Beceri",
    description: "Ortamdaki kurallara uygun davranma becerisi için zincirleme beceri analizi.",
    order: 21,
    steps: [
      "Kuralı dinler.",
      "Kuralı anlar.",
      "Kurala uygun davranmaya başlar.",
      "Kurala uyar.",
      "Başkalarının haklarına saygı gösterir.",
      "Gerektiğinde kendini durdurur.",
      "Kurala uygun davranmayı sürdürür.",
      "Uyarıları dikkate alır.",
      "Etkinliği tamamlar.",
      "Kurala uymayı sonlandırmadan devam ettirir.",
    ],
  },
  {
    name: "Duygu Tanıma",
    category: "Sosyal Beceri",
    description: "Karşısındaki kişinin duygusunu fark edip adlandırma becerisi için zincirleme beceri analizi.",
    order: 22,
    steps: [
      "Karşısındaki kişiye bakar.",
      "Yüz ifadesini inceler.",
      "Beden dilini gözlemler.",
      "Ses tonunu dinler.",
      "Duyguyu tahmin eder.",
      "Duyguyu söyler.",
      "Gerekçesini açıklar.",
      "Uygun tepki verir.",
      "Etkileşimi sürdürür.",
      "Etkinliği tamamlar.",
    ],
  },
  {
    name: "Empati Gösterme",
    category: "Sosyal Beceri",
    description: "Karşısındaki kişinin duygusunu anlayıp uygun destek sunma becerisi için zincirleme beceri analizi.",
    order: 23,
    steps: [
      "Karşısındaki kişiyi dinler.",
      "Duygusunu fark eder.",
      "Göz teması kurar.",
      "Uygun ifade kullanır.",
      "Duygusunu anladığını belirtir.",
      "Destek sunar.",
      "Karşı tarafı dinlemeye devam eder.",
      "Yargılamaz.",
      "Nazik davranır.",
      "Etkileşimi tamamlar.",
    ],
  },
  {
    name: "Problem Çözme",
    category: "Sosyal Beceri",
    description: "Karşılaştığı bir problemi adım adım çözme becerisi için zincirleme beceri analizi.",
    order: 24,
    steps: [
      "Problemi fark eder.",
      "Sakin kalır.",
      "Problemi tanımlar.",
      "Çözüm seçenekleri düşünür.",
      "En uygun seçeneği belirler.",
      "Çözümü uygular.",
      "Sonucu değerlendirir.",
      "Gerekirse farklı çözüm dener.",
      "Problemi çözer.",
      "Etkinliğe devam eder.",
    ],
  },
  {
    name: "Çatışma Çözme",
    category: "Sosyal Beceri",
    description: "Başka biriyle yaşanan bir çatışmayı uzlaşarak çözme becerisi için zincirleme beceri analizi.",
    order: 25,
    steps: [
      "Çatışmayı fark eder.",
      "Sakinleşir.",
      "Karşı tarafı dinler.",
      "Kendi görüşünü açıklar.",
      "Karşı tarafın görüşünü dinler.",
      "Ortak çözüm önerir.",
      "Uzlaşmayı kabul eder.",
      "Anlaşmaya uyar.",
      "Olumlu iletişimi sürdürür.",
      "Çatışmayı sonlandırır.",
    ],
  },
  {
    name: "Soru Sorma",
    category: "Sosyal Beceri",
    description: "Merak ettiği bir konuda uygun şekilde soru sorma becerisi için zincirleme beceri analizi.",
    order: 26,
    steps: [
      "Merak ettiği konuyu belirler.",
      "İlgili kişiye yönelir.",
      "Göz teması kurar.",
      "Nazikçe seslenir.",
      "Sorusunu açık ifade eder.",
      "Cevabı dinler.",
      "Gerekirse ek soru sorar.",
      "Teşekkür eder.",
      "Bilgiyi kullanır.",
      "Etkinliğe devam eder.",
    ],
  },
  {
    name: "Soruya Cevap Verme",
    category: "Sosyal Beceri",
    description: "Kendisine sorulan bir soruya uygun şekilde cevap verme becerisi için zincirleme beceri analizi.",
    order: 27,
    steps: [
      "Soruyu dinler.",
      "Soruyu anlar.",
      "Düşünür.",
      "Göz teması kurar.",
      "Uygun cevap verir.",
      "Ses tonunu ayarlar.",
      "Gerekirse açıklama yapar.",
      "Karşı tarafın tepkisini bekler.",
      "Sohbeti sürdürür.",
      "Etkileşimi tamamlar.",
    ],
  },
  {
    name: "Telefon Görüşmesi Yapma",
    category: "Sosyal Beceri",
    description: "Telefonla görüşme başlatma ve sürdürme becerisi için zincirleme beceri analizi.",
    order: 28,
    steps: [
      "Telefonu hazırlar.",
      "Doğru kişiyi seçer.",
      "Aramayı başlatır.",
      "Selam verir.",
      "Kendini tanıtır.",
      "Konuşma amacını söyler.",
      "Karşı tarafı dinler.",
      "Gerekli bilgiyi paylaşır.",
      "Teşekkür eder.",
      "Görüşmeyi uygun şekilde sonlandırır.",
    ],
  },
  {
    name: "Tanımadığı Biriyle İletişim Kurma",
    category: "Sosyal Beceri",
    description: "Tanımadığı biriyle güvenli ve uygun şekilde iletişim kurma becerisi için zincirleme beceri analizi.",
    order: 29,
    steps: [
      "Kişiyi fark eder.",
      "Yanına yaklaşır.",
      "Göz teması kurar.",
      "Selam verir.",
      "Kendini tanıtır.",
      "Konuşma amacını söyler.",
      "Karşı tarafı dinler.",
      "Nazik ifadeler kullanır.",
      "Teşekkür eder.",
      "Etkileşimi uygun şekilde sonlandırır.",
    ],
  },
  {
    name: "Öğretmenden Söz İsteme",
    category: "Sosyal Beceri",
    description: "Sınıf ortamında öğretmenden konuşma izni isteme becerisi için zincirleme beceri analizi.",
    order: 30,
    steps: [
      "Öğretmeni dinler.",
      "Konuşmak istediğini fark eder.",
      "Elini kaldırır.",
      "Sessizce bekler.",
      "Söz verilmesini bekler.",
      "Ayağa kalkar (gerekiyorsa).",
      "Konuşmasını yapar.",
      "Soruya cevap verir veya soru sorar.",
      "Teşekkür eder.",
      "Yerine oturur.",
    ],
  },
  // Kişisel Bakım Becerileri
  {
    name: "El Yıkama",
    category: "Kişisel Bakım Becerileri",
    description: "Temel hijyen becerisi için zincirleme beceri analizi.",
    order: 31,
    steps: [
      "Lavaboya gider.",
      "Musluğu açar.",
      "Ellerini ıslatır.",
      "Sabun alır.",
      "Ellerini köpürtür.",
      "Parmak aralarını temizler.",
      "Tırnak çevresini ovalar.",
      "Ellerini durular.",
      "Musluğu kapatır.",
      "Ellerini havlu ile kurular.",
    ],
  },
  {
    name: "Diş Fırçalama",
    category: "Kişisel Bakım Becerileri",
    description: "Günlük diş bakımı becerisi için zincirleme beceri analizi.",
    order: 32,
    steps: [
      "Diş fırçasını alır.",
      "Macunu açar.",
      "Fırçaya macun sürer.",
      "Üst dişleri fırçalar.",
      "Alt dişleri fırçalar.",
      "Çiğneme yüzeylerini fırçalar.",
      "Dilini temizler.",
      "Ağzını çalkalar.",
      "Fırçayı yıkar.",
      "Malzemeleri yerine koyar.",
    ],
  },
  {
    name: "Yüz Yıkama",
    category: "Kişisel Bakım Becerileri",
    description: "Yüz temizliği becerisi için zincirleme beceri analizi.",
    order: 33,
    steps: [
      "Lavaboya gider.",
      "Musluğu açar.",
      "Ellerini ıslatır.",
      "Yüzünü ıslatır.",
      "Temizleyici kullanır (gerekiyorsa).",
      "Yüzünü ovalar.",
      "Durular.",
      "Musluğu kapatır.",
      "Havlu ile kurular.",
      "Havluyu yerine asar.",
    ],
  },
  {
    name: "Saç Tarama",
    category: "Kişisel Bakım Becerileri",
    description: "Kişisel bakım becerisi için zincirleme beceri analizi.",
    order: 34,
    steps: [
      "Tarağı alır.",
      "Aynanın karşısına geçer.",
      "Saçını kontrol eder.",
      "Ön kısmı tarar.",
      "Yanları tarar.",
      "Arka kısmı tarar.",
      "Düğümleri açar.",
      "Saçını düzenler.",
      "Tarağı temizler.",
      "Yerine koyar.",
    ],
  },
  {
    name: "Giyinme",
    category: "Kişisel Bakım Becerileri",
    description: "Bağımsız giyinme becerisi için zincirleme beceri analizi.",
    order: 35,
    steps: [
      "Giysilerini seçer.",
      "İç çamaşırını giyer.",
      "Alt giysisini giyer.",
      "Üst giysisini giyer.",
      "Çorabını giyer.",
      "Ayakkabısını giyer.",
      "Fermuarını çeker.",
      "Düğmelerini ilikler.",
      "Kıyafetini düzeltir.",
      "Aynadan kontrol eder.",
    ],
  },
  {
    name: "Soyunma",
    category: "Kişisel Bakım Becerileri",
    description: "Bağımsız soyunma becerisi için zincirleme beceri analizi.",
    order: 36,
    steps: [
      "Ayakkabısını çıkarır.",
      "Çorabını çıkarır.",
      "Üst giysisini çıkarır.",
      "Alt giysisini çıkarır.",
      "İç çamaşırını çıkarır.",
      "Kirli çamaşırları ayırır.",
      "Çamaşır sepetine koyar.",
      "Dolabı düzenler.",
      "Odayı kontrol eder.",
      "İşlemi tamamlar.",
    ],
  },
  {
    name: "Ayakkabı Bağlama",
    category: "Kişisel Bakım Becerileri",
    description: "İnce motor beceri analizine örnek zincirleme beceri.",
    order: 37,
    steps: [
      "Ayakkabıyı giyer.",
      "Bağcıkları düzeltir.",
      "İki ucu eşitler.",
      "İlk düğümü yapar.",
      "İlk halka oluşturur.",
      "Diğer bağcığı dolandırır.",
      "İkinci halkayı oluşturur.",
      "Düğümü sıkar.",
      "Bağcıkları kontrol eder.",
      "Ayağa kalkar.",
    ],
  },
  {
    name: "Tuvalet Kullanma",
    category: "Kişisel Bakım Becerileri",
    description: "Bağımsız tuvalet kullanma becerisi için zincirleme beceri analizi.",
    order: 38,
    steps: [
      "Tuvalete gider.",
      "Kapıyı kapatır.",
      "Giysisini uygun şekilde indirir.",
      "Tuvaleti kullanır.",
      "Tuvalet kağıdını kullanır.",
      "Sifonu çeker.",
      "Giysisini düzeltir.",
      "Ellerini yıkar.",
      "Kurular.",
      "Tuvaletten çıkar.",
    ],
  },
  {
    name: "Banyo Yapma",
    category: "Kişisel Bakım Becerileri",
    description: "Bağımsız banyo yapma becerisi için zincirleme beceri analizi.",
    order: 39,
    steps: [
      "Gerekli malzemeleri hazırlar.",
      "Suyu ayarlar.",
      "Giysilerini çıkarır.",
      "Vücudunu ıslatır.",
      "Sabun veya şampuan kullanır.",
      "Vücudunu temizler.",
      "Durulanır.",
      "Havlu ile kurulanır.",
      "Temiz kıyafetlerini giyer.",
      "Banyoyu düzenler.",
    ],
  },
  {
    name: "Tırnak Kesme",
    category: "Kişisel Bakım Becerileri",
    description: "Kişisel bakım becerisi için zincirleme beceri analizi.",
    order: 40,
    steps: [
      "Tırnak makasını alır.",
      "Uygun yere oturur.",
      "Tırnaklarını kontrol eder.",
      "El tırnaklarını keser.",
      "Diğer eli keser.",
      "Ayak tırnaklarını keser.",
      "Kesilen parçaları toplar.",
      "Ellerini yıkar.",
      "Makası yerine koyar.",
      "İşlemi tamamlar.",
    ],
  },
  // Mutfak Becerileri
  {
    name: "Su İçme",
    category: "Mutfak Becerileri",
    description: "Bağımsız su içme becerisi için zincirleme beceri analizi.",
    order: 41,
    steps: [
      "Bardağı alır.",
      "Musluğu açar.",
      "Bardağı doldurur.",
      "Musluğu kapatır.",
      "Bardağı tutar.",
      "Suyu içer.",
      "Bardağı boşaltır.",
      "Lavaboya götürür.",
      "Yıkar.",
      "Yerine koyar.",
    ],
  },
  {
    name: "Masa Hazırlama",
    category: "Mutfak Becerileri",
    description: "Sofra hazırlama becerisi için zincirleme beceri analizi.",
    order: 42,
    steps: [
      "Masayı kontrol eder.",
      "Masa örtüsünü serer.",
      "Tabak koyar.",
      "Çatal koyar.",
      "Kaşık koyar.",
      "Bıçak koyar.",
      "Bardak koyar.",
      "Peçete koyar.",
      "Düzeni kontrol eder.",
      "Hazırlığı tamamlar.",
    ],
  },
  {
    name: "Sofrayı Toplama",
    category: "Mutfak Becerileri",
    description: "Yemek sonrası sofra toplama becerisi için zincirleme beceri analizi.",
    order: 43,
    steps: [
      "Kirli tabakları toplar.",
      "Bardakları toplar.",
      "Çatal-kaşıkları toplar.",
      "Artıkları çöpe döker.",
      "Malzemeleri mutfağa götürür.",
      "Masayı siler.",
      "Sandalyeleri düzeltir.",
      "Masa örtüsünü kaldırır.",
      "Malzemeleri yerleştirir.",
      "İşlemi tamamlar.",
    ],
  },
  {
    name: "Sandviç Hazırlama",
    category: "Mutfak Becerileri",
    description: "Basit yemek hazırlama becerisi için zincirleme beceri analizi.",
    order: 44,
    steps: [
      "Malzemeleri hazırlar.",
      "Ekmeği çıkarır.",
      "İç malzemesini hazırlar.",
      "Ekmeğe sürer.",
      "İç malzemesini yerleştirir.",
      "Ekmeği kapatır.",
      "Sandviçi keser.",
      "Tabağa koyar.",
      "Masaya getirir.",
      "Malzemeleri toplar.",
    ],
  },
  {
    name: "Meyve Yıkama",
    category: "Mutfak Becerileri",
    description: "Mutfakta temizlik becerisi için zincirleme beceri analizi.",
    order: 45,
    steps: [
      "Meyveyi seçer.",
      "Musluğu açar.",
      "Meyveyi su altında tutar.",
      "Ovalayarak temizler.",
      "Durular.",
      "Musluğu kapatır.",
      "Kurular.",
      "Servis tabağına koyar.",
      "Tezgâhı temizler.",
      "İşlemi tamamlar.",
    ],
  },
  // Ev Yaşamı Becerileri
  {
    name: "Yatağını Toplama",
    category: "Ev Yaşamı Becerileri",
    description: "Günlük yaşam becerisi için zincirleme beceri analizi.",
    order: 46,
    steps: [
      "Yorganı düzeltir.",
      "Çarşafı düzeltir.",
      "Yastığı yerleştirir.",
      "Battaniyeyi katlar.",
      "Yatağı kontrol eder.",
      "Düzgün görünüm sağlar.",
      "Odayı kontrol eder.",
      "Gereksiz eşyaları kaldırır.",
      "Perdeleri düzenler.",
      "İşlemi tamamlar.",
    ],
  },
  {
    name: "Odayı Toplama",
    category: "Ev Yaşamı Becerileri",
    description: "Günlük yaşam becerisi için zincirleme beceri analizi.",
    order: 47,
    steps: [
      "Oyuncakları toplar.",
      "Kitapları kaldırır.",
      "Çöpleri toplar.",
      "Kirli kıyafetleri ayırır.",
      "Masa düzenini sağlar.",
      "Sandalyeleri düzeltir.",
      "Zemini kontrol eder.",
      "Gereksiz eşyaları kaldırır.",
      "Son kontrolü yapar.",
      "Odayı düzenli bırakır.",
    ],
  },
  {
    name: "Çöp Atma",
    category: "Ev Yaşamı Becerileri",
    description: "Günlük yaşam becerisi için zincirleme beceri analizi.",
    order: 48,
    steps: [
      "Çöpü belirler.",
      "Çöp poşetini bağlar.",
      "Poşeti dikkatlice taşır.",
      "Çöp kutusuna gider.",
      "Poşeti kutuya bırakır.",
      "Yeni poşet takar.",
      "Ellerini yıkar.",
      "Çevreyi kontrol eder.",
      "Geri dönüşümü ayırır (gerekiyorsa).",
      "İşlemi tamamlar.",
    ],
  },
  {
    name: "Çamaşır Sepetine Koyma",
    category: "Ev Yaşamı Becerileri",
    description: "Günlük yaşam becerisi için zincirleme beceri analizi.",
    order: 49,
    steps: [
      "Kirli kıyafeti belirler.",
      "Çamaşırı katlamadan taşır.",
      "Sepeti bulur.",
      "Çamaşırı sepete bırakır.",
      "Renk ayrımı yapar (gerekiyorsa).",
      "Çevreyi kontrol eder.",
      "Başka kirli çamaşır varsa toplar.",
      "Sepeti düzenler.",
      "Ellerini temizler.",
      "İşlemi tamamlar.",
    ],
  },
  {
    name: "Bitki Sulama",
    category: "Ev Yaşamı Becerileri",
    description: "Günlük yaşam becerisi için zincirleme beceri analizi.",
    order: 50,
    steps: [
      "Sulanacak bitkiyi belirler.",
      "Sulama kabını alır.",
      "Su doldurur.",
      "Bitkiye yaklaşır.",
      "Toprağı kontrol eder.",
      "Uygun miktarda su verir.",
      "Taşan suyu temizler.",
      "Sulama kabını boşaltır.",
      "Yerine koyar.",
      "İşlemi tamamlar.",
    ],
  },
  // Toplumsal Yaşam Becerileri
  {
    name: "Alışveriş Yapma",
    category: "Toplumsal Yaşam Becerileri",
    description: "Toplumsal yaşam becerisi için zincirleme beceri analizi.",
    order: 51,
    steps: [
      "Alınacak ürünü belirler.",
      "Listeyi kontrol eder.",
      "Markete girer.",
      "Ürünü bulur.",
      "Ürünü sepete koyar.",
      "Kasaya gider.",
      "Ödemeyi yapar.",
      "Para üstünü alır.",
      "Fişini alır.",
      "Marketten çıkar.",
    ],
  },
  {
    name: "Para Kullanma",
    category: "Toplumsal Yaşam Becerileri",
    description: "Toplumsal yaşam becerisi için zincirleme beceri analizi.",
    order: 52,
    steps: [
      "Ürünün fiyatını öğrenir.",
      "Cüzdanını açar.",
      "Doğru parayı seçer.",
      "Kasiyere uzatır.",
      "Para üstünü alır.",
      "Kontrol eder.",
      "Cüzdanına koyar.",
      "Fişini alır.",
      "Teşekkür eder.",
      "İşlemi tamamlar.",
    ],
  },
  {
    name: "Toplu Taşıma Kullanma",
    category: "Toplumsal Yaşam Becerileri",
    description: "Toplumsal yaşam becerisi için zincirleme beceri analizi.",
    order: 53,
    steps: [
      "Gideceği yeri belirler.",
      "Doğru durağa gider.",
      "Aracı bekler.",
      "Doğru araca biner.",
      "Kartını okutur.",
      "Uygun yere oturur veya tutunur.",
      "Durağını takip eder.",
      "İneceği durakta hazırlanır.",
      "Araçtan iner.",
      "Güvenli şekilde uzaklaşır.",
    ],
  },
  {
    name: "Karşıdan Karşıya Geçme",
    category: "Toplumsal Yaşam Becerileri",
    description: "Trafik güvenliği becerisi için zincirleme beceri analizi.",
    order: 54,
    steps: [
      "Kaldırımda bekler.",
      "Yaya geçidini belirler.",
      "Trafik ışığını kontrol eder.",
      "Sağa bakar.",
      "Sola bakar.",
      "Tekrar sağa bakar.",
      "Güvenli olduğundan emin olur.",
      "Yürümeye başlar.",
      "Koşmadan geçer.",
      "Kaldırıma çıkar.",
    ],
  },
  {
    name: "Acil Durumda Yardım İsteme",
    category: "Toplumsal Yaşam Becerileri",
    description: "Güvenlik becerisi için zincirleme beceri analizi.",
    order: 55,
    steps: [
      "Acil durumu fark eder.",
      "Güvenli bir yere geçer.",
      "Yakındaki yetişkini belirler.",
      "Yardım ister.",
      "Gerekiyorsa 112'yi arar.",
      "Adresini söyler.",
      "Durumu açıklar.",
      "Soruları cevaplar.",
      "Güvenli yerde bekler.",
      "Yardım gelince bilgi verir.",
    ],
  },
  // Akademik Beceriler
  {
    name: "Adını Yazma",
    category: "Akademik Beceriler",
    description: "Akademik beceri için zincirleme beceri analizi.",
    order: 56,
    steps: [
      "Kalemi doğru şekilde tutar.",
      "Defteri uygun konuma getirir.",
      "Yazacağı alanı belirler.",
      "İlk harfi yazar.",
      "Sonraki harfleri sırayla yazar.",
      "Harfleri doğru yönde oluşturur.",
      "Harfler arasında uygun boşluk bırakır.",
      "Adını tamamlar.",
      "Yazdığını kontrol eder.",
      "Kalemi bırakır.",
    ],
  },
  {
    name: "Kopya Yazma",
    category: "Akademik Beceriler",
    description: "Akademik beceri için zincirleme beceri analizi.",
    order: 57,
    steps: [
      "Yazıyı inceler.",
      "İlk harfi belirler.",
      "Kalemi hazırlar.",
      "Harfi yazar.",
      "Kelimeyi tamamlar.",
      "Satır düzenini korur.",
      "Noktalama işaretlerini yazar.",
      "Yazısını kontrol eder.",
      "Eksikleri düzeltir.",
      "Yazmayı tamamlar.",
    ],
  },
  {
    name: "Kitap Okuma",
    category: "Akademik Beceriler",
    description: "Akademik beceri için zincirleme beceri analizi.",
    order: 58,
    steps: [
      "Kitabı alır.",
      "Doğru yönde tutar.",
      "İlk sayfayı açar.",
      "Satırı takip eder.",
      "Kelimeleri okur.",
      "Noktalamaya dikkat eder.",
      "Sayfayı çevirir.",
      "Okumayı sürdürür.",
      "Kitabı kapatır.",
      "Yerine koyar.",
    ],
  },
  {
    name: "Harf Tanıma",
    category: "Akademik Beceriler",
    description: "Akademik beceri için zincirleme beceri analizi.",
    order: 59,
    steps: [
      "Harfi görür.",
      "Harfe dikkat eder.",
      "Şeklini inceler.",
      "Harfi söyler.",
      "Benzer harflerden ayırır.",
      "Yazılışını gösterir.",
      "Sesini söyler.",
      "Kelime içinde bulur.",
      "Doğru eşleştirir.",
      "Etkinliği tamamlar.",
    ],
  },
  {
    name: "Hece Okuma",
    category: "Akademik Beceriler",
    description: "Akademik beceri için zincirleme beceri analizi.",
    order: 60,
    steps: [
      "Heceye bakar.",
      "İlk sesi tanır.",
      "İkinci sesi tanır.",
      "Sesleri birleştirir.",
      "Heceyi okur.",
      "Tekrar eder.",
      "Yeni heceye geçer.",
      "Doğru okur.",
      "Kontrol eder.",
      "Tamamlar.",
    ],
  },
  {
    name: "Kelime Okuma",
    category: "Akademik Beceriler",
    description: "Akademik beceri için zincirleme beceri analizi.",
    order: 61,
    steps: [
      "Kelimeye bakar.",
      "İlk sesi belirler.",
      "Harfleri takip eder.",
      "Sesleri birleştirir.",
      "Kelimeyi okur.",
      "Anlamını söyler.",
      "Tekrar okur.",
      "Sonraki kelimeye geçer.",
      "Akıcı okur.",
      "Tamamlar.",
    ],
  },
  {
    name: "Sayı Sayma",
    category: "Akademik Beceriler",
    description: "Akademik beceri için zincirleme beceri analizi.",
    order: 62,
    steps: [
      "Saymaya hazırlanır.",
      "İlk sayıyı söyler.",
      "Sırayla devam eder.",
      "Atlama yapmaz.",
      "Doğru ritimde sayar.",
      "Hedef sayıya ulaşır.",
      "Saymayı durdurur.",
      "Kontrol eder.",
      "Tekrar eder.",
      "Tamamlar.",
    ],
  },
  {
    name: "Nesne Sayma",
    category: "Akademik Beceriler",
    description: "Akademik beceri için zincirleme beceri analizi.",
    order: 63,
    steps: [
      "Nesneleri inceler.",
      "İlk nesneyi işaret eder.",
      "Bir der.",
      "Her nesneyi bir kez sayar.",
      "Saymaya devam eder.",
      "Son nesneyi sayar.",
      "Toplamı söyler.",
      "Kontrol eder.",
      "Tekrar eder.",
      "Tamamlar.",
    ],
  },
  {
    name: "Toplama İşlemi",
    category: "Akademik Beceriler",
    description: "Akademik beceri için zincirleme beceri analizi.",
    order: 64,
    steps: [
      "İşleme bakar.",
      "Sayıları belirler.",
      "Gerekirse materyal kullanır.",
      "İlk sayıyı sayar.",
      "İkinci sayıyı ekler.",
      "Toplamı bulur.",
      "Sonucu söyler.",
      "Yazar.",
      "Kontrol eder.",
      "Tamamlar.",
    ],
  },
  {
    name: "Çıkarma İşlemi",
    category: "Akademik Beceriler",
    description: "Akademik beceri için zincirleme beceri analizi.",
    order: 65,
    steps: [
      "İşleme bakar.",
      "İlk sayıyı belirler.",
      "Çıkacak sayıyı belirler.",
      "Materyal kullanır.",
      "Çıkarmayı yapar.",
      "Sonucu bulur.",
      "Sonucu söyler.",
      "Yazar.",
      "Kontrol eder.",
      "Tamamlar.",
    ],
  },
  // Dil ve İletişim Becerileri
  {
    name: "İki Basamaklı Yönergeyi Takip Etme",
    category: "Dil ve İletişim Becerileri",
    description: "Dil ve iletişim becerisi için zincirleme beceri analizi.",
    order: 66,
    steps: [
      "Yönergeyi dinler.",
      "İlk görevi belirler.",
      "İkinci görevi belirler.",
      "İlk görevi yapar.",
      "İkinci görevi yapar.",
      "Sırayı bozmaz.",
      "Görevleri tamamlar.",
      "Öğretmene döner.",
      "Tamamladığını belirtir.",
      "Bekler.",
    ],
  },
  {
    name: "Üç Basamaklı Yönergeyi Takip Etme",
    category: "Dil ve İletişim Becerileri",
    description: "Dil ve iletişim becerisi için zincirleme beceri analizi.",
    order: 67,
    steps: [
      "Yönergeyi dinler.",
      "Birinci görevi hatırlar.",
      "İkinci görevi hatırlar.",
      "Üçüncü görevi hatırlar.",
      "İlkini yapar.",
      "İkincisini yapar.",
      "Üçüncüsünü yapar.",
      "Kontrol eder.",
      "Tamamladığını söyler.",
      "Bekler.",
    ],
  },
  {
    name: "Resim Adlandırma",
    category: "Dil ve İletişim Becerileri",
    description: "Dil ve iletişim becerisi için zincirleme beceri analizi.",
    order: 68,
    steps: [
      "Resme bakar.",
      "Nesneyi tanır.",
      "Adını düşünür.",
      "Söyler.",
      "Doğru telaffuz eder.",
      "Öğretmeni dinler.",
      "Gerekirse tekrar eder.",
      "Sonraki resme geçer.",
      "Cevabını kontrol eder.",
      "Tamamlar.",
    ],
  },
  {
    name: "Cümle Kurma",
    category: "Dil ve İletişim Becerileri",
    description: "Dil ve iletişim becerisi için zincirleme beceri analizi.",
    order: 69,
    steps: [
      "Konuyu belirler.",
      "İlk kelimeyi seçer.",
      "İkinci kelimeyi seçer.",
      "Cümleyi tamamlar.",
      "Doğru sıra kullanır.",
      "Sesli söyler.",
      "Anlam kontrolü yapar.",
      "Gerekirse düzeltir.",
      "Tekrar eder.",
      "Tamamlar.",
    ],
  },
  {
    name: "Hikâye Anlatma",
    category: "Dil ve İletişim Becerileri",
    description: "Dil ve iletişim becerisi için zincirleme beceri analizi.",
    order: 70,
    steps: [
      "Konuyu belirler.",
      "Başlangıcı söyler.",
      "Olayları sırayla anlatır.",
      "Karakterleri açıklar.",
      "Mekânı söyler.",
      "Sonucu anlatır.",
      "Dinleyiciye bakar.",
      "Uygun ses tonu kullanır.",
      "Soruları cevaplar.",
      "Bitirir.",
    ],
  },
  // Bilişsel Beceriler
  {
    name: "Renk Eşleştirme",
    category: "Bilişsel Beceriler",
    description: "Bilişsel beceri için zincirleme beceri analizi.",
    order: 71,
    steps: [
      "Renkleri inceler.",
      "İlk rengi belirler.",
      "Aynı rengi bulur.",
      "Eşleştirir.",
      "Sonraki renge geçer.",
      "Tüm renkleri tamamlar.",
      "Kontrol eder.",
      "Hataları düzeltir.",
      "Öğretmene gösterir.",
      "Tamamlar.",
    ],
  },
  {
    name: "Şekil Eşleştirme",
    category: "Bilişsel Beceriler",
    description: "Bilişsel beceri için zincirleme beceri analizi.",
    order: 72,
    steps: [
      "Şekli inceler.",
      "Aynısını arar.",
      "Doğru şekli seçer.",
      "Eşleştirir.",
      "Sonraki şekle geçer.",
      "Tümünü tamamlar.",
      "Kontrol eder.",
      "Düzeltir.",
      "Gösterir.",
      "Tamamlar.",
    ],
  },
  {
    name: "Sınıflandırma",
    category: "Bilişsel Beceriler",
    description: "Bilişsel beceri için zincirleme beceri analizi.",
    order: 73,
    steps: [
      "Nesneleri inceler.",
      "Özelliği belirler.",
      "İlk nesneyi seçer.",
      "Doğru gruba koyar.",
      "Sonraki nesneyi seçer.",
      "Gruplamayı sürdürür.",
      "Kontrol eder.",
      "Düzeltir.",
      "Tamamlar.",
      "Öğretmene gösterir.",
    ],
  },
  {
    name: "Örüntü Tamamlama",
    category: "Bilişsel Beceriler",
    description: "Bilişsel beceri için zincirleme beceri analizi.",
    order: 74,
    steps: [
      "Örüntüyü inceler.",
      "Kuralı belirler.",
      "Eksik bölümü fark eder.",
      "Doğru parçayı seçer.",
      "Yerleştirir.",
      "Kontrol eder.",
      "Sonraki örüntüye geçer.",
      "Tamamlar.",
      "Gösterir.",
      "Bitirir.",
    ],
  },
  {
    name: "Saat Okuma (Tam Saat)",
    category: "Bilişsel Beceriler",
    description: "Bilişsel beceri için zincirleme beceri analizi.",
    order: 75,
    steps: [
      "Saate bakar.",
      "Kısa akrebi bulur.",
      "Uzun yelkovanı bulur.",
      "Tam saati belirler.",
      "Saati söyler.",
      "Kontrol eder.",
      "Tekrar eder.",
      "Yeni saate geçer.",
      "Doğru cevap verir.",
      "Tamamlar.",
    ],
  },
  // Ev Yaşamı Becerileri (ek)
  {
    name: "Çamaşır Makinesi Kullanma",
    category: "Ev Yaşamı Becerileri",
    description: "Günlük yaşam becerisi için zincirleme beceri analizi.",
    order: 76,
    steps: [
      "Kirlileri renklerine göre ayırır.",
      "Çamaşırları makineye yerleştirir.",
      "Deterjanı uygun bölmeye koyar.",
      "Gerekirse yumuşatıcı ekler.",
      "Makinenin kapağını kapatır.",
      "Uygun programı seçer.",
      "Makineyi çalıştırır.",
      "Programın bitmesini bekler.",
      "Çamaşırları makineden çıkarır.",
      "Makine kapağını açık bırakır.",
    ],
  },
  {
    name: "Elektrikli Süpürge Kullanma",
    category: "Ev Yaşamı Becerileri",
    description: "Günlük yaşam becerisi için zincirleme beceri analizi.",
    order: 77,
    steps: [
      "Süpürgeyi hazırlar.",
      "Fişi prize takar.",
      "Açma düğmesine basar.",
      "Süpürülecek alanı belirler.",
      "Zemini sistemli şekilde süpürür.",
      "Köşeleri süpürür.",
      "Süpürmeyi tamamlar.",
      "Süpürgeyi kapatır.",
      "Fişi prizden çıkarır.",
      "Süpürgeyi yerine kaldırır.",
    ],
  },
  {
    name: "Yer Silme",
    category: "Ev Yaşamı Becerileri",
    description: "Günlük yaşam becerisi için zincirleme beceri analizi.",
    order: 78,
    steps: [
      "Kovayı hazırlar.",
      "Su doldurur.",
      "Temizlik malzemesini ekler.",
      "Paspası ıslatır.",
      "Fazla suyunu sıkar.",
      "Zemini uygun sırayla siler.",
      "Kirli bölgeleri tekrar siler.",
      "Paspası temizler.",
      "Suyu boşaltır.",
      "Malzemeleri yerine kaldırır.",
    ],
  },
  {
    name: "Toz Alma",
    category: "Ev Yaşamı Becerileri",
    description: "Günlük yaşam becerisi için zincirleme beceri analizi.",
    order: 79,
    steps: [
      "Bez hazırlar.",
      "Gerekirse temizleyici kullanır.",
      "Toz alınacak alanı belirler.",
      "Üst yüzeyleri siler.",
      "Rafları siler.",
      "Masayı siler.",
      "Elektronik eşyaları dikkatli siler.",
      "Bezini temizler.",
      "Malzemeleri yerine koyar.",
      "Alanı kontrol eder.",
    ],
  },
  {
    name: "Kıyafet Katlama",
    category: "Ev Yaşamı Becerileri",
    description: "Günlük yaşam becerisi için zincirleme beceri analizi.",
    order: 80,
    steps: [
      "Kıyafeti düz zemine serer.",
      "Kırışıklıkları düzeltir.",
      "Kolları içe katlar.",
      "Yanları katlar.",
      "Alt kısmı katlar.",
      "Düzgün şekil oluşturur.",
      "Katlamayı kontrol eder.",
      "Gerekirse düzeltir.",
      "Dolaba götürür.",
      "Yerine yerleştirir.",
    ],
  },
  {
    name: "Askıya Kıyafet Asma",
    category: "Ev Yaşamı Becerileri",
    description: "Günlük yaşam becerisi için zincirleme beceri analizi.",
    order: 81,
    steps: [
      "Askıyı alır.",
      "Kıyafeti düzeltir.",
      "Askıya geçirir.",
      "Omuzlarını yerleştirir.",
      "Düğme veya fermuarı kapatır (gerekiyorsa).",
      "Askıyı dolaba götürür.",
      "Askılığı yerine asar.",
      "Düzgün durduğunu kontrol eder.",
      "Dolabı düzenler.",
      "Kapağı kapatır.",
    ],
  },
  {
    name: "Dolap Düzenleme",
    category: "Ev Yaşamı Becerileri",
    description: "Günlük yaşam becerisi için zincirleme beceri analizi.",
    order: 82,
    steps: [
      "Dolabı açar.",
      "Kıyafetleri çıkarır.",
      "Türlerine göre ayırır.",
      "Katlanacakları katlar.",
      "Askılık kullanılacakları asar.",
      "Rafları düzenler.",
      "Gereksiz eşyaları çıkarır.",
      "Düzeni kontrol eder.",
      "Dolabı kapatır.",
      "İşlemi tamamlar.",
    ],
  },
  {
    name: "Çanta Hazırlama",
    category: "Ev Yaşamı Becerileri",
    description: "Günlük yaşam becerisi için zincirleme beceri analizi.",
    order: 83,
    steps: [
      "Gidilecek yeri belirler.",
      "Gerekli eşyaları listeler.",
      "Çantayı açar.",
      "Büyük eşyaları yerleştirir.",
      "Küçük eşyaları yerleştirir.",
      "Kişisel eşyaları ekler.",
      "Fermuarı kapatır.",
      "Eksikleri kontrol eder.",
      "Çantayı taşımaya hazırlar.",
      "Yanına alır.",
    ],
  },
  {
    name: "Takvim Kullanma",
    category: "Ev Yaşamı Becerileri",
    description: "Günlük yaşam becerisi için zincirleme beceri analizi.",
    order: 84,
    steps: [
      "Takvimi açar.",
      "Günü bulur.",
      "Tarihi söyler.",
      "Ayı belirler.",
      "Haftanın gününü söyler.",
      "Planlanan etkinliği kontrol eder.",
      "Gerekirse not ekler.",
      "Sonraki tarihi inceler.",
      "Takvimi kapatır.",
      "İşlemi tamamlar.",
    ],
  },
  // Mutfak Becerileri (ek)
  {
    name: "Bulaşık Makinesi Kullanma",
    category: "Mutfak Becerileri",
    description: "Mutfak becerisi için zincirleme beceri analizi.",
    order: 85,
    steps: [
      "Kirli bulaşıkları toplar.",
      "Artıkları çöpe döker.",
      "Bulaşıkları uygun raflara yerleştirir.",
      "Çatal-kaşıkları sepete koyar.",
      "Deterjanı yerleştirir.",
      "Kapağı kapatır.",
      "Program seçer.",
      "Makineyi çalıştırır.",
      "Program bitince bulaşıkları çıkarır.",
      "Temiz bulaşıkları dolaba yerleştirir.",
    ],
  },
  {
    name: "Yumurta Haşlama",
    category: "Mutfak Becerileri",
    description: "Mutfak becerisi için zincirleme beceri analizi.",
    order: 86,
    steps: [
      "Yumurtaları seçer.",
      "Tencereye yerleştirir.",
      "Üzerini geçecek kadar su ekler.",
      "Ocağı açar.",
      "Kaynamasını bekler.",
      "Uygun süre pişirir.",
      "Ocağı kapatır.",
      "Yumurtaları soğuk suya alır.",
      "Kabuğunu soyar.",
      "Servise hazırlar.",
    ],
  },
  {
    name: "Çay Hazırlama",
    category: "Mutfak Becerileri",
    description: "Mutfak becerisi için zincirleme beceri analizi.",
    order: 87,
    steps: [
      "Çaydanlığı hazırlar.",
      "Alt demliğe su koyar.",
      "Üst demliğe çay ekler.",
      "Ocağı açar.",
      "Su kaynayınca çayı demler.",
      "Demlenmesini bekler.",
      "Çayı bardağa doldurur.",
      "İstenirse sıcak su ekler.",
      "Ocağı kapatır.",
      "Çaydanlığı güvenli şekilde kaldırır.",
    ],
  },
  {
    name: "Kahvaltı Hazırlama",
    category: "Mutfak Becerileri",
    description: "Mutfak becerisi için zincirleme beceri analizi.",
    order: 88,
    steps: [
      "Gerekli malzemeleri belirler.",
      "Tabakları hazırlar.",
      "Bardakları koyar.",
      "Peynir vb. yiyecekleri çıkarır.",
      "Ekmek hazırlar.",
      "İçeceği hazırlar.",
      "Masayı düzenler.",
      "Kahvaltıyı servise sunar.",
      "Kullanılmayan ürünleri kaldırır.",
      "Kahvaltıya hazır hale getirir.",
    ],
  },
  {
    name: "Mikrodalga Kullanma",
    category: "Mutfak Becerileri",
    description: "Mutfak becerisi için zincirleme beceri analizi.",
    order: 89,
    steps: [
      "Isıtılacak yiyeceği hazırlar.",
      "Uygun kaba koyar.",
      "Mikrodalgaya yerleştirir.",
      "Kapağı kapatır.",
      "Süreyi ayarlar.",
      "Çalıştırır.",
      "Süre bitene kadar bekler.",
      "Dikkatlice çıkarır.",
      "Isısını kontrol eder.",
      "Mikrodalgayı temiz bırakır.",
    ],
  },
  {
    name: "Buzdolabına Yiyecek Yerleştirme",
    category: "Mutfak Becerileri",
    description: "Mutfak becerisi için zincirleme beceri analizi.",
    order: 90,
    steps: [
      "Ürünleri kontrol eder.",
      "Bozuk ürünleri ayırır.",
      "Rafları belirler.",
      "Soğuk ürünleri uygun rafa koyar.",
      "Sebzeleri sebzeliğe yerleştirir.",
      "İçecekleri uygun bölmeye koyar.",
      "Kapak raflarını düzenler.",
      "Kapağı kapatır.",
      "Düzeni kontrol eder.",
      "İşlemi tamamlar.",
    ],
  },
  // Kişisel Bakım Becerileri (ek)
  {
    name: "İlaç Saatini Takip Etme",
    category: "Kişisel Bakım Becerileri",
    description: "Kişisel bakım becerisi için zincirleme beceri analizi.",
    order: 91,
    steps: [
      "İlaç saatini kontrol eder.",
      "Doğru ilacı belirler.",
      "Doğru dozu kontrol eder.",
      "Gerekli suyu hazırlar.",
      "İlacı alır.",
      "Su içer.",
      "İlacı yerine koyar.",
      "Alındığını işaretler.",
      "Saati tekrar kontrol eder.",
      "İşlemi tamamlar.",
    ],
  },
  // Toplumsal Yaşam Becerileri (ek)
  {
    name: "Randevuya Zamanında Gitme",
    category: "Toplumsal Yaşam Becerileri",
    description: "Toplumsal yaşam becerisi için zincirleme beceri analizi.",
    order: 92,
    steps: [
      "Randevu saatini kontrol eder.",
      "Hazırlık süresini planlar.",
      "Gerekli eşyaları hazırlar.",
      "Evden zamanında çıkar.",
      "Ulaşım aracını kullanır.",
      "Adresi takip eder.",
      "Randevu yerine ulaşır.",
      "Giriş işlemini yapar.",
      "Bekleme alanında bekler.",
      "Randevuya katılır.",
    ],
  },
  {
    name: "Telefon Rehberinden Kişi Arama",
    category: "Toplumsal Yaşam Becerileri",
    description: "Toplumsal yaşam becerisi için zincirleme beceri analizi.",
    order: 93,
    steps: [
      "Telefonu açar.",
      "Rehberi açar.",
      "Aranacak kişiyi bulur.",
      "İsmini kontrol eder.",
      "Arama tuşuna basar.",
      "Telefonun açılmasını bekler.",
      "Selam verir.",
      "Konuşmasını yapar.",
      "Görüşmeyi sonlandırır.",
      "Telefonu kapatır.",
    ],
  },
  {
    name: "Asansör Kullanma",
    category: "Toplumsal Yaşam Becerileri",
    description: "Toplumsal yaşam becerisi için zincirleme beceri analizi.",
    order: 94,
    steps: [
      "Asansörün önüne gider.",
      "Çağırma düğmesine basar.",
      "Kabinin gelmesini bekler.",
      "İçerideki kişilerin çıkmasını bekler.",
      "Asansöre biner.",
      "Gideceği katın düğmesine basar.",
      "Güvenli şekilde bekler.",
      "Katına gelince çıkar.",
      "Kapının kapanmasına engel olmaz.",
      "Yoluna devam eder.",
    ],
  },
  {
    name: "ATM Kullanma (İleri Düzey)",
    category: "Toplumsal Yaşam Becerileri",
    description: "Toplumsal yaşam becerisi için zincirleme beceri analizi.",
    order: 95,
    steps: [
      "ATM'ye yaklaşır.",
      "Kartını yerleştirir.",
      "Şifresini girer.",
      "İşlem türünü seçer.",
      "Tutarı girer.",
      "İşlemi onaylar.",
      "Parasını alır.",
      "Kartını alır.",
      "Fişini alır.",
      "ATM'den ayrılır.",
    ],
  },
  {
    name: "Banka İşlemi Yapma (İleri Düzey)",
    category: "Toplumsal Yaşam Becerileri",
    description: "Toplumsal yaşam becerisi için zincirleme beceri analizi.",
    order: 96,
    steps: [
      "Bankaya gider.",
      "Sıra numarası alır.",
      "Sırasını bekler.",
      "Gişeye gider.",
      "Kimliğini veya kartını verir.",
      "İşlem talebini açıklar.",
      "Evrakları kontrol eder.",
      "Gerekli imzayı atar.",
      "İşlem sonucunu alır.",
      "Bankadan ayrılır.",
    ],
  },
  {
    name: "Kargo Gönderme",
    category: "Toplumsal Yaşam Becerileri",
    description: "Toplumsal yaşam becerisi için zincirleme beceri analizi.",
    order: 97,
    steps: [
      "Gönderilecek ürünü hazırlar.",
      "Ürünü uygun şekilde paketler.",
      "Alıcı bilgilerini hazırlar.",
      "Kargo şubesine gider.",
      "Görevliye teslim eder.",
      "Gönderi bilgilerini verir.",
      "Ücreti öder.",
      "Takip numarasını alır.",
      "Makbuzu saklar.",
      "Şubeden ayrılır.",
    ],
  },
  {
    name: "Fatura Ödeme",
    category: "Toplumsal Yaşam Becerileri",
    description: "Toplumsal yaşam becerisi için zincirleme beceri analizi.",
    order: 98,
    steps: [
      "Ödenecek faturayı belirler.",
      "Son ödeme tarihini kontrol eder.",
      "Ödeme yöntemini seçer.",
      "Gerekli bilgileri girer.",
      "Tutarı kontrol eder.",
      "Ödemeyi onaylar.",
      "İşlem sonucunu bekler.",
      "Dekontu alır veya kaydeder.",
      "Ödemenin tamamlandığını kontrol eder.",
      "İşlemi sonlandırır.",
    ],
  },
];

async function main() {
  for (const template of templates) {
    await prisma.skillTemplate.upsert({
      where: { name: template.name },
      create: {
        name: template.name,
        category: template.category,
        description: template.description,
        steps: template.steps,
        order: template.order,
        isActive: true,
      },
      // Var olan kayıt dokunulmaz bırakılır: admin panelinden yapılan elle
      // düzenlemeler her deploy'da bu seed tarafından ezilmesin.
      update: {},
    });
  }

  console.log(`Seeded ${templates.length} skill templates.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
